version: '3.8'
services:
  tensorflow:
    image: tensorflow/serving:latest
    ports:
      - '8502:8502'
    volumes:
      - .:/backend
    command:
      - --rest_api_port=8502
      - --model_config_file=/backend/models.config
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - tensorflow